name: PR Tests

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - feat/github-actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read Python version from .python-version  and run tests
      id: python_version
      run: |
        python_version=$(cat infrastructure/api/.python-version)
        echo "python-version=$python_version" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python-version }}

    - name: Install uv and dependencies
      run: |
        cd infrastructure/api/
        pip install uv
        uv sync

    - name: Run unit tests
      run: |
        cd infrastructure/api/tests
        uv run pytest test_root.py

    - name: Check if Terraform directory exists
      id: check_terraform_dir
      run: |
        if [ -d "infrastructure/terraform" ]; then
          echo "Terraform directory found, initializing Terraform."
          echo "terraform_dir_exists=true" >> $GITHUB_ENV
          terraform -chdir=infrastructure/terraform init
        else
          echo "Terraform directory not found, skipping Terraform initialization."
          echo "terraform_dir_exists=false" >> $GITHUB_ENV
        fi

    - name: Terraform Validate
      if: success() && github.env.terraform_dir_exists == 'true'
      run: terraform -chdir=infrastructure/terraform validate